Repository metabase/shoppy, pull requests merged in 2025-02, with the labels that each got.

#94 Use default question layout and adjust theming
  package.json
  src/components/CreateQuestionView.tsx
  src/components/InteractiveQuestionView.tsx
  src/routes/analytics/DashboardPage.tsx
  src/routes/analytics/QuestionPage.tsx
  src/routes/analytics/new/NewFromScratchPage.tsx
  src/routes/analytics/new/NewFromTemplatePage.tsx
  src/routes/product-detail/ProductDetailInsights.tsx
  src/themes/luminara.css
  src/themes/proficiency.ts
  src/themes/stitch.ts
  yarn.lock
Labels: enhancement

#99 Update demo link in the README.md
  README.md
Labels: documentation

#100 Change tailwind config export type
  tailwind.config.js
Labels: bug
